export type Country = {
  code: string;
  name: string;
  flag: string;
  confederation: string;
};

export type User = {
  discordId: string;
  username: string;
  avatar: string;
  points: number;
  countryCode: string;
};

export type Match = {
  id: string;
  stage: string;
  group?: string;
  roundIndex?: number;
  kickoff: string;
  venue: string;
  homeCountryCode: string;
  awayCountryCode: string;
  score: {
    home: number;
    away: number;
  } | null;
};

export const COUNTRIES: Country[] = [
  // CONMEBOL (6)
  { code: 'ARG', name: 'Argentina', flag: '🇦🇷', confederation: 'CONMEBOL' },
  { code: 'BRA', name: 'Brasil', flag: '🇧🇷', confederation: 'CONMEBOL' },
  { code: 'COL', name: 'Colombia', flag: '🇨🇴', confederation: 'CONMEBOL' },
  { code: 'ECU', name: 'Ecuador', flag: '🇪🇨', confederation: 'CONMEBOL' },
  { code: 'URU', name: 'Uruguay', flag: '🇺🇾', confederation: 'CONMEBOL' },
  { code: 'PAR', name: 'Paraguay', flag: '🇵🇾', confederation: 'CONMEBOL' },

  // CONCACAF (6)
  { code: 'USA', name: 'Estados Unidos', flag: '🇺🇸', confederation: 'CONCACAF' },
  { code: 'MEX', name: 'México', flag: '🇲🇽', confederation: 'CONCACAF' },
  { code: 'CAN', name: 'Canadá', flag: '🇨🇦', confederation: 'CONCACAF' },
  { code: 'PAN', name: 'Panamá', flag: '🇵🇦', confederation: 'CONCACAF' },
  { code: 'CUW', name: 'Curazao', flag: '🇨🇼', confederation: 'CONCACAF' },
  { code: 'HTI', name: 'Haití', flag: '🇭🇹', confederation: 'CONCACAF' },

  // UEFA (16)
  { code: 'GER', name: 'Alemania', flag: '🇩🇪', confederation: 'UEFA' },
  { code: 'BIH', name: 'Bosnia y Herzegovina', flag: '🇧🇦', confederation: 'UEFA' },
  { code: 'AUT', name: 'Austria', flag: '🇦🇹', confederation: 'UEFA' },
  { code: 'BEL', name: 'Bélgica', flag: '🇧🇪', confederation: 'UEFA' },
  { code: 'CRO', name: 'Croacia', flag: '🇭🇷', confederation: 'UEFA' },
  { code: 'ESP', name: 'España', flag: '🇪🇸', confederation: 'UEFA' },
  { code: 'FRA', name: 'Francia', flag: '🇫🇷', confederation: 'UEFA' },
  { code: 'ENG', name: 'Inglaterra', flag: '🏴', confederation: 'UEFA' },
  { code: 'NOR', name: 'Noruega', flag: '🇳🇴', confederation: 'UEFA' },
  { code: 'NED', name: 'Países Bajos', flag: '🇳🇱', confederation: 'UEFA' },
  { code: 'POR', name: 'Portugal', flag: '🇵🇹', confederation: 'UEFA' },
  { code: 'CZE', name: 'República Checa', flag: '🇨🇿', confederation: 'UEFA' },
  { code: 'SCO', name: 'Escocia', flag: '🏴', confederation: 'UEFA' },
  { code: 'SWE', name: 'Suecia', flag: '🇸🇪', confederation: 'UEFA' },
  { code: 'SUI', name: 'Suiza', flag: '🇨🇭', confederation: 'UEFA' },
  { code: 'TUR', name: 'Turquía', flag: '🇹🇷', confederation: 'UEFA' },

  // CAF (10)
  { code: 'ALG', name: 'Argelia', flag: '🇩🇿', confederation: 'CAF' },
  { code: 'CPV', name: 'Cabo Verde', flag: '🇨🇻', confederation: 'CAF' },
  { code: 'CIV', name: 'Costa de Marfil', flag: '🇨🇮', confederation: 'CAF' },
  { code: 'COD', name: 'RD de Congo/Jamaica', flag: '🇨🇩', confederation: 'CAF' },
  { code: 'EGY', name: 'Egipto', flag: '🇪🇬', confederation: 'CAF' },
  { code: 'GHA', name: 'Ghana', flag: '🇬🇭', confederation: 'CAF' },
  { code: 'MAR', name: 'Marruecos', flag: '🇲🇦', confederation: 'CAF' },
  { code: 'SEN', name: 'Senegal', flag: '🇸🇳', confederation: 'CAF' },
  { code: 'RSA', name: 'Sudáfrica', flag: '🇿🇦', confederation: 'CAF' },
  { code: 'TUN', name: 'Túnez', flag: '🇹🇳', confederation: 'CAF' },

  // AFC (9)
  { code: 'KSA', name: 'Arabia Saudita', flag: '🇸🇦', confederation: 'AFC' },
  { code: 'AUS', name: 'Australia', flag: '🇦🇺', confederation: 'AFC' },
  { code: 'IRQ', name: 'Irak', flag: '🇮🇶', confederation: 'AFC' },
  { code: 'IRN', name: 'Irán', flag: '🇮🇷', confederation: 'AFC' },
  { code: 'JPN', name: 'Japón', flag: '🇯🇵', confederation: 'AFC' },
  { code: 'JOR', name: 'Jordania', flag: '🇯🇴', confederation: 'AFC' },
  { code: 'QAT', name: 'Qatar', flag: '🇶🇦', confederation: 'AFC' },
  { code: 'KOR', name: 'Corea del Sur', flag: '🇰🇷', confederation: 'AFC' },
  { code: 'UZB', name: 'Uzbekistán', flag: '🇺🇿', confederation: 'AFC' },

  // OFC (1)
  { code: 'NZL', name: 'Nueva Zelanda', flag: '🇳🇿', confederation: 'OFC' },
];

export const USERS: User[] = [
  { discordId: '179134666626826241', username: 'titoelguan', avatar: '99505af5b3f2f18b9dedbc217e7dfb98', points: 150, countryCode: 'URU' },
  { discordId: '104000000000000001', username: 'Ballester', avatar: 'a1b2c3d4e5f6', points: 142, countryCode: 'ARG' },
  { discordId: '104000000000000002', username: 'Nico', avatar: 'b1c2d3e4f5a6', points: 130, countryCode: 'BRA' },
  { discordId: '104000000000000003', username: 'Agus', avatar: 'c1d2e3f4a5b6', points: 120, countryCode: 'FRA' },
  { discordId: '104000000000000004', username: 'Mati', avatar: 'd1e2f3a4b5c6', points: 110, countryCode: 'ESP' },
  { discordId: '104000000000000005', username: 'Lucho', avatar: 'e1f2a3b4c5d6', points: 98, countryCode: 'GER' },
  { discordId: '104000000000000006', username: 'Pablo', avatar: 'f1a2b3c4d5e6', points: 92, countryCode: 'MEX' },
  { discordId: '104000000000000007', username: 'Santi', avatar: '112233445566', points: 87, countryCode: 'ENG' },
  { discordId: '104000000000000008', username: 'Vale', avatar: '223344556677', points: 80, countryCode: 'POR' },
  { discordId: '104000000000000009', username: 'Fran', avatar: '334455667788', points: 74, countryCode: 'JPN' },
];

export const MATCHES: Match[] = [
  // GRUPOS (A-L)
  {
    id: 'A1',
    stage: 'Grupos',
    group: 'A',
    roundIndex: 1,
    kickoff: '2026-06-11T15:00:00Z',
    venue: 'Estadio Ciudad de México',
    homeCountryCode: 'MEX',
    awayCountryCode: 'RSA',
    score: null,
  },
  {
    id: 'A2',
    stage: 'Grupos',
    group: 'A',
    roundIndex: 2,
    kickoff: '2026-06-11T22:00:00Z',
    venue: 'Estadio Guadalajara',
    homeCountryCode: 'KOR',
    awayCountryCode: 'CZE',
    score: null,
  },
  {
    id: 'A3',
    stage: 'Grupos',
    group: 'A',
    roundIndex: 3,
    kickoff: '2026-06-18T12:00:00Z',
    venue: 'Atlanta Stadium',
    homeCountryCode: 'CZE',
    awayCountryCode: 'RSA',
    score: null,
  },
  {
    id: 'A4',
    stage: 'Grupos',
    group: 'A',
    roundIndex: 4,
    kickoff: '2026-06-18T21:00:00Z',
    venue: 'Estadio Guadalajara',
    homeCountryCode: 'MEX',
    awayCountryCode: 'KOR',
    score: null,
  },
  {
    id: 'A5',
    stage: 'Grupos',
    group: 'A',
    roundIndex: 5,
    kickoff: '2026-06-24T21:00:00Z',
    venue: 'Estadio Ciudad de México',
    homeCountryCode: 'CZE',
    awayCountryCode: 'MEX',
    score: null,
  },
  {
    id: 'A6',
    stage: 'Grupos',
    group: 'A',
    roundIndex: 6,
    kickoff: '2026-06-24T21:00:00Z',
    venue: 'Estadio Monterrey',
    homeCountryCode: 'RSA',
    awayCountryCode: 'KOR',
    score: null,
  },
  {
    id: 'B1',
    stage: 'Grupos',
    group: 'B',
    roundIndex: 1,
    kickoff: '2026-06-12T15:00:00Z',
    venue: 'Toronto Stadium',
    homeCountryCode: 'CAN',
    awayCountryCode: 'BIH',
    score: null,
  },
  {
    id: 'B2',
    stage: 'Grupos',
    group: 'B',
    roundIndex: 2,
    kickoff: '2026-06-13T15:00:00Z',
    venue: 'San Francisco Bay Area Stadium',
    homeCountryCode: 'QAT',
    awayCountryCode: 'SUI',
    score: null,
  },
  {
    id: 'B3',
    stage: 'Grupos',
    group: 'B',
    roundIndex: 3,
    kickoff: '2026-06-18T15:00:00Z',
    venue: 'Los Angeles Stadium',
    homeCountryCode: 'SUI',
    awayCountryCode: 'BIH',
    score: null,
  },
  {
    id: 'B4',
    stage: 'Grupos',
    group: 'B',
    roundIndex: 4,
    kickoff: '2026-06-18T18:00:00Z',
    venue: 'BC Place Vancouver',
    homeCountryCode: 'CAN',
    awayCountryCode: 'QAT',
    score: null,
  },
  {
    id: 'B5',
    stage: 'Grupos',
    group: 'B',
    roundIndex: 5,
    kickoff: '2026-06-24T15:00:00Z',
    venue: 'BC Place Vancouver',
    homeCountryCode: 'SUI',
    awayCountryCode: 'CAN',
    score: null,
  },
  {
    id: 'B6',
    stage: 'Grupos',
    group: 'B',
    roundIndex: 6,
    kickoff: '2026-06-24T15:00:00Z',
    venue: 'Seattle Stadium',
    homeCountryCode: 'BIH',
    awayCountryCode: 'QAT',
    score: null,
  },
  {
    id: 'C1',
    stage: 'Grupos',
    group: 'C',
    roundIndex: 1,
    kickoff: '2026-06-13T18:00:00Z',
    venue: 'Nueva York Nueva Jersey Stadium',
    homeCountryCode: 'BRA',
    awayCountryCode: 'MAR',
    score: null,
  },
  {
    id: 'C2',
    stage: 'Grupos',
    group: 'C',
    roundIndex: 2,
    kickoff: '2026-06-13T21:00:00Z',
    venue: 'Boston Stadium',
    homeCountryCode: 'HTI',
    awayCountryCode: 'SCO',
    score: null,
  },
  {
    id: 'C3',
    stage: 'Grupos',
    group: 'C',
    roundIndex: 3,
    kickoff: '2026-06-19T18:00:00Z',
    venue: 'Boston Stadium',
    homeCountryCode: 'SCO',
    awayCountryCode: 'MAR',
    score: null,
  },
  {
    id: 'C4',
    stage: 'Grupos',
    group: 'C',
    roundIndex: 4,
    kickoff: '2026-06-19T21:00:00Z',
    venue: 'Philadelphia Stadium',
    homeCountryCode: 'BRA',
    awayCountryCode: 'HTI',
    score: null,
  },
  {
    id: 'C5',
    stage: 'Grupos',
    group: 'C',
    roundIndex: 5,
    kickoff: '2026-06-24T18:00:00Z',
    venue: 'Miami Stadium',
    homeCountryCode: 'BRA',
    awayCountryCode: 'SCO',
    score: null,
  },
  {
    id: 'C6',
    stage: 'Grupos',
    group: 'C',
    roundIndex: 6,
    kickoff: '2026-06-24T18:00:00Z',
    venue: 'Atlanta Stadium',
    homeCountryCode: 'MAR',
    awayCountryCode: 'HTI',
    score: null,
  },
  {
    id: 'D1',
    stage: 'Grupos',
    group: 'D',
    roundIndex: 1,
    kickoff: '2026-06-12T21:00:00Z',
    venue: 'Los Angeles Stadium',
    homeCountryCode: 'USA',
    awayCountryCode: 'PAR',
    score: null,
  },
  {
    id: 'D2',
    stage: 'Grupos',
    group: 'D',
    roundIndex: 2,
    kickoff: '2026-06-13T00:00:00Z',
    venue: 'BC Place Vancouver',
    homeCountryCode: 'AUS',
    awayCountryCode: 'TUR',
    score: null,
  },
  {
    id: 'D3',
    stage: 'Grupos',
    group: 'D',
    roundIndex: 3,
    kickoff: '2026-06-19T15:00:00Z',
    venue: 'Seattle Stadium',
    homeCountryCode: 'USA',
    awayCountryCode: 'AUS',
    score: null,
  },
  {
    id: 'D4',
    stage: 'Grupos',
    group: 'D',
    roundIndex: 4,
    kickoff: '2026-06-19T00:00:00Z',
    venue: 'San Francisco Bay Area Stadium',
    homeCountryCode: 'TUR',
    awayCountryCode: 'PAR',
    score: null,
  },
  {
    id: 'D5',
    stage: 'Grupos',
    group: 'D',
    roundIndex: 5,
    kickoff: '2026-06-25T22:00:00Z',
    venue: 'Los Angeles Stadium',
    homeCountryCode: 'TUR',
    awayCountryCode: 'USA',
    score: null,
  },
  {
    id: 'D6',
    stage: 'Grupos',
    group: 'D',
    roundIndex: 6,
    kickoff: '2026-06-25T22:00:00Z',
    venue: 'San Francisco Bay Area Stadium',
    homeCountryCode: 'PAR',
    awayCountryCode: 'AUS',
    score: null,
  },
  {
    id: 'E1',
    stage: 'Grupos',
    group: 'E',
    roundIndex: 1,
    kickoff: '2026-06-14T13:00:00Z',
    venue: 'Houston Stadium',
    homeCountryCode: 'GER',
    awayCountryCode: 'CUW',
    score: null,
  },
  {
    id: 'E2',
    stage: 'Grupos',
    group: 'E',
    roundIndex: 2,
    kickoff: '2026-06-14T19:00:00Z',
    venue: 'Philadelphia Stadium',
    homeCountryCode: 'CIV',
    awayCountryCode: 'ECU',
    score: null,
  },
  {
    id: 'E3',
    stage: 'Grupos',
    group: 'E',
    roundIndex: 3,
    kickoff: '2026-06-20T16:00:00Z',
    venue: 'Toronto Stadium',
    homeCountryCode: 'GER',
    awayCountryCode: 'CIV',
    score: null,
  },
  {
    id: 'E4',
    stage: 'Grupos',
    group: 'E',
    roundIndex: 4,
    kickoff: '2026-06-20T22:00:00Z',
    venue: 'Kansas City Stadium',
    homeCountryCode: 'ECU',
    awayCountryCode: 'CUW',
    score: null,
  },
  {
    id: 'E5',
    stage: 'Grupos',
    group: 'E',
    roundIndex: 5,
    kickoff: '2026-06-25T16:00:00Z',
    venue: 'Philadelphia Stadium',
    homeCountryCode: 'CUW',
    awayCountryCode: 'CIV',
    score: null,
  },
  {
    id: 'E6',
    stage: 'Grupos',
    group: 'E',
    roundIndex: 6,
    kickoff: '2026-06-25T16:00:00Z',
    venue: 'New York New Jersey Stadium',
    homeCountryCode: 'ECU',
    awayCountryCode: 'GER',
    score: null,
  },
  {
    id: 'F1',
    stage: 'Grupos',
    group: 'F',
    roundIndex: 1,
    kickoff: '2026-06-14T16:00:00Z',
    venue: 'Dallas Stadium',
    homeCountryCode: 'NED',
    awayCountryCode: 'JPN',
    score: null,
  },
  {
    id: 'F2',
    stage: 'Grupos',
    group: 'F',
    roundIndex: 2,
    kickoff: '2026-06-14T22:00:00Z',
    venue: 'Estadio Monterrey',
    homeCountryCode: 'SWE',
    awayCountryCode: 'TUN',
    score: null,
  },
  {
    id: 'F3',
    stage: 'Grupos',
    group: 'F',
    roundIndex: 3,
    kickoff: '2026-06-20T13:00:00Z',
    venue: 'Houston Stadium',
    homeCountryCode: 'NED',
    awayCountryCode: 'SWE',
    score: null,
  },
  {
    id: 'F4',
    stage: 'Grupos',
    group: 'F',
    roundIndex: 4,
    kickoff: '2026-06-20T00:00:00Z',
    venue: 'Estadio Monterrey',
    homeCountryCode: 'TUN',
    awayCountryCode: 'JPN',
    score: null,
  },
  {
    id: 'F5',
    stage: 'Grupos',
    group: 'F',
    roundIndex: 5,
    kickoff: '2026-06-25T19:00:00Z',
    venue: 'Dallas Stadium',
    homeCountryCode: 'JPN',
    awayCountryCode: 'SWE',
    score: null,
  },
  {
    id: 'F6',
    stage: 'Grupos',
    group: 'F',
    roundIndex: 6,
    kickoff: '2026-06-25T19:00:00Z',
    venue: 'Kansas City Stadium',
    homeCountryCode: 'TUN',
    awayCountryCode: 'NED',
    score: null,
  },
  {
    id: 'G1',
    stage: 'Grupos',
    group: 'G',
    roundIndex: 1,
    kickoff: '2026-06-15T15:00:00Z',
    venue: 'Seattle Stadium',
    homeCountryCode: 'BEL',
    awayCountryCode: 'EGY',
    score: null,
  },
  {
    id: 'G2',
    stage: 'Grupos',
    group: 'G',
    roundIndex: 2,
    kickoff: '2026-06-15T21:00:00Z',
    venue: 'Los Angeles Stadium',
    homeCountryCode: 'IRN',
    awayCountryCode: 'NZL',
    score: null,
  },
  {
    id: 'G3',
    stage: 'Grupos',
    group: 'G',
    roundIndex: 3,
    kickoff: '2026-06-21T15:00:00Z',
    venue: 'Los Angeles Stadium',
    homeCountryCode: 'BEL',
    awayCountryCode: 'IRN',
    score: null,
  },
  {
    id: 'G4',
    stage: 'Grupos',
    group: 'G',
    roundIndex: 4,
    kickoff: '2026-06-21T21:00:00Z',
    venue: 'BC Place Vancouver',
    homeCountryCode: 'NZL',
    awayCountryCode: 'EGY',
    score: null,
  },
  {
    id: 'G5',
    stage: 'Grupos',
    group: 'G',
    roundIndex: 5,
    kickoff: '2026-06-26T23:00:00Z',
    venue: 'Seattle Stadium',
    homeCountryCode: 'EGY',
    awayCountryCode: 'IRN',
    score: null,
  },
  {
    id: 'G6',
    stage: 'Grupos',
    group: 'G',
    roundIndex: 6,
    kickoff: '2026-06-26T23:00:00Z',
    venue: 'BC Place Vancouver',
    homeCountryCode: 'NZL',
    awayCountryCode: 'BEL',
    score: null,
  },
  {
    id: 'H1',
    stage: 'Grupos',
    group: 'H',
    roundIndex: 1,
    kickoff: '2026-06-15T12:00:00Z',
    venue: 'Atlanta Stadium',
    homeCountryCode: 'ESP',
    awayCountryCode: 'CPV',
    score: null,
  },
  {
    id: 'H2',
    stage: 'Grupos',
    group: 'H',
    roundIndex: 2,
    kickoff: '2026-06-15T18:00:00Z',
    venue: 'Miami Stadium',
    homeCountryCode: 'KSA',
    awayCountryCode: 'URU',
    score: null,
  },
  {
    id: 'H3',
    stage: 'Grupos',
    group: 'H',
    roundIndex: 3,
    kickoff: '2026-06-21T12:00:00Z',
    venue: 'Atlanta Stadium',
    homeCountryCode: 'ESP',
    awayCountryCode: 'KSA',
    score: null,
  },
  {
    id: 'H4',
    stage: 'Grupos',
    group: 'H',
    roundIndex: 4,
    kickoff: '2026-06-21T18:00:00Z',
    venue: 'Miami Stadium',
    homeCountryCode: 'URU',
    awayCountryCode: 'CPV',
    score: null,
  },
  {
    id: 'H5',
    stage: 'Grupos',
    group: 'H',
    roundIndex: 5,
    kickoff: '2026-06-26T20:00:00Z',
    venue: 'Houston Stadium',
    homeCountryCode: 'CPV',
    awayCountryCode: 'KSA',
    score: null,
  },
  {
    id: 'H6',
    stage: 'Grupos',
    group: 'H',
    roundIndex: 6,
    kickoff: '2026-06-26T20:00:00Z',
    venue: 'Estadio Guadalajara',
    homeCountryCode: 'URU',
    awayCountryCode: 'ESP',
    score: null,
  },
  {
    id: 'I1',
    stage: 'Grupos',
    group: 'I',
    roundIndex: 1,
    kickoff: '2026-06-16T15:00:00Z',
    venue: 'New York New Jersey Stadium',
    homeCountryCode: 'FRA',
    awayCountryCode: 'SEN',
    score: null,
  },
  {
    id: 'I2',
    stage: 'Grupos',
    group: 'I',
    roundIndex: 2,
    kickoff: '2026-06-16T18:00:00Z',
    venue: 'Boston Stadium',
    homeCountryCode: 'IRQ',
    awayCountryCode: 'NOR',
    score: null,
  },
  {
    id: 'I3',
    stage: 'Grupos',
    group: 'I',
    roundIndex: 3,
    kickoff: '2026-06-22T17:00:00Z',
    venue: 'Philadelphia Stadium',
    homeCountryCode: 'FRA',
    awayCountryCode: 'IRQ',
    score: null,
  },
  {
    id: 'I4',
    stage: 'Grupos',
    group: 'I',
    roundIndex: 4,
    kickoff: '2026-06-22T20:00:00Z',
    venue: 'Nueva York Nueva Jersey Stadium',
    homeCountryCode: 'NOR',
    awayCountryCode: 'SEN',
    score: null,
  },
  {
    id: 'I5',
    stage: 'Grupos',
    group: 'I',
    roundIndex: 5,
    kickoff: '2026-06-26T15:00:00Z',
    venue: 'Boston Stadium',
    homeCountryCode: 'NOR',
    awayCountryCode: 'FRA',
    score: null,
  },
  {
    id: 'I6',
    stage: 'Grupos',
    group: 'I',
    roundIndex: 6,
    kickoff: '2026-06-26T15:00:00Z',
    venue: 'Toronto Stadium',
    homeCountryCode: 'SEN',
    awayCountryCode: 'IRQ',
    score: null,
  },
  {
    id: 'J1',
    stage: 'Grupos',
    group: 'J',
    roundIndex: 1,
    kickoff: '2026-06-16T21:00:00Z',
    venue: 'Kansas City Stadium',
    homeCountryCode: 'ARG',
    awayCountryCode: 'ALG',
    score: null,
  },
  {
    id: 'J2',
    stage: 'Grupos',
    group: 'J',
    roundIndex: 2,
    kickoff: '2026-06-16T00:00:00Z',
    venue: 'San Francisco Bay Area Stadium',
    homeCountryCode: 'AUT',
    awayCountryCode: 'JOR',
    score: null,
  },
  {
    id: 'J3',
    stage: 'Grupos',
    group: 'J',
    roundIndex: 3,
    kickoff: '2026-06-22T13:00:00Z',
    venue: 'Dallas Stadium',
    homeCountryCode: 'ARG',
    awayCountryCode: 'AUT',
    score: null,
  },
  {
    id: 'J4',
    stage: 'Grupos',
    group: 'J',
    roundIndex: 4,
    kickoff: '2026-06-22T23:00:00Z',
    venue: 'San Francisco Bay Area Stadium',
    homeCountryCode: 'JOR',
    awayCountryCode: 'ALG',
    score: null,
  },
  {
    id: 'J5',
    stage: 'Grupos',
    group: 'J',
    roundIndex: 5,
    kickoff: '2026-06-27T22:00:00Z',
    venue: 'Kansas City Stadium',
    homeCountryCode: 'ALG',
    awayCountryCode: 'AUT',
    score: null,
  },
  {
    id: 'J6',
    stage: 'Grupos',
    group: 'J',
    roundIndex: 6,
    kickoff: '2026-06-27T22:00:00Z',
    venue: 'Dallas Stadium',
    homeCountryCode: 'JOR',
    awayCountryCode: 'ARG',
    score: null,
  },
  {
    id: 'K1',
    stage: 'Grupos',
    group: 'K',
    roundIndex: 1,
    kickoff: '2026-06-17T13:00:00Z',
    venue: 'Houston Stadium',
    homeCountryCode: 'POR',
    awayCountryCode: 'COD',
    score: null,
  },
  {
    id: 'K2',
    stage: 'Grupos',
    group: 'K',
    roundIndex: 2,
    kickoff: '2026-06-17T22:00:00Z',
    venue: 'Estadio Ciudad de México',
    homeCountryCode: 'UZB',
    awayCountryCode: 'COL',
    score: null,
  },
  {
    id: 'K3',
    stage: 'Grupos',
    group: 'K',
    roundIndex: 3,
    kickoff: '2026-06-23T13:00:00Z',
    venue: 'Houston Stadium',
    homeCountryCode: 'POR',
    awayCountryCode: 'UZB',
    score: null,
  },
  {
    id: 'K4',
    stage: 'Grupos',
    group: 'K',
    roundIndex: 4,
    kickoff: '2026-06-23T22:00:00Z',
    venue: 'Estadio Guadalajara',
    homeCountryCode: 'COL',
    awayCountryCode: 'COD',
    score: null,
  },
  {
    id: 'K5',
    stage: 'Grupos',
    group: 'K',
    roundIndex: 5,
    kickoff: '2026-06-27T19:30:00Z',
    venue: 'Miami Stadium',
    homeCountryCode: 'COL',
    awayCountryCode: 'POR',
    score: null,
  },
  {
    id: 'K6',
    stage: 'Grupos',
    group: 'K',
    roundIndex: 6,
    kickoff: '2026-06-27T19:30:00Z',
    venue: 'Atlanta Stadium',
    homeCountryCode: 'COD',
    awayCountryCode: 'UZB',
    score: null,
  },
  {
    id: 'L1',
    stage: 'Grupos',
    group: 'L',
    roundIndex: 1,
    kickoff: '2026-06-17T16:00:00Z',
    venue: 'Dallas Stadium',
    homeCountryCode: 'ENG',
    awayCountryCode: 'CRO',
    score: null,
  },
  {
    id: 'L2',
    stage: 'Grupos',
    group: 'L',
    roundIndex: 2,
    kickoff: '2026-06-17T19:00:00Z',
    venue: 'Toronto Stadium',
    homeCountryCode: 'GHA',
    awayCountryCode: 'PAN',
    score: null,
  },
  {
    id: 'L3',
    stage: 'Grupos',
    group: 'L',
    roundIndex: 3,
    kickoff: '2026-06-23T16:00:00Z',
    venue: 'Boston Stadium',
    homeCountryCode: 'ENG',
    awayCountryCode: 'GHA',
    score: null,
  },
  {
    id: 'L4',
    stage: 'Grupos',
    group: 'L',
    roundIndex: 4,
    kickoff: '2026-06-23T19:00:00Z',
    venue: 'Toronto Stadium',
    homeCountryCode: 'PAN',
    awayCountryCode: 'CRO',
    score: null,
  },
  {
    id: 'L5',
    stage: 'Grupos',
    group: 'L',
    roundIndex: 5,
    kickoff: '2026-06-27T17:00:00Z',
    venue: 'New York New Jersey Stadium',
    homeCountryCode: 'PAN',
    awayCountryCode: 'ENG',
    score: null,
  },
  {
    id: 'L6',
    stage: 'Grupos',
    group: 'L',
    roundIndex: 6,
    kickoff: '2026-06-27T17:00:00Z',
    venue: 'Philadelphia Stadium',
    homeCountryCode: 'CRO',
    awayCountryCode: 'GHA',
    score: null,
  },

  // 16AVOS (32 equipos)
  {
    id: 'R32-1',
    stage: '16avos',
    roundIndex: 1,
    kickoff: '2026-07-01T20:00:00Z',
    venue: 'Los Angeles',
    homeCountryCode: 'ARG',
    awayCountryCode: 'POR',
    score: null,
  },
  { id: 'R32-2', stage: '16avos', roundIndex: 2, kickoff: '2026-07-03T20:00:00Z', venue: 'Seattle', homeCountryCode: 'BRA', awayCountryCode: 'SEN', score: null },
  { id: 'R32-3', stage: '16avos', roundIndex: 3, kickoff: '2026-07-03T23:00:00Z', venue: 'Miami', homeCountryCode: 'USA', awayCountryCode: 'CRO', score: null },
  { id: 'R32-4', stage: '16avos', roundIndex: 4, kickoff: '2026-07-04T20:00:00Z', venue: 'Toronto', homeCountryCode: 'MEX', awayCountryCode: 'GER', score: null },
  { id: 'R32-5', stage: '16avos', roundIndex: 5, kickoff: '2026-07-04T23:00:00Z', venue: 'Boston', homeCountryCode: 'ENG', awayCountryCode: 'AUS', score: null },
  { id: 'R32-6', stage: '16avos', roundIndex: 6, kickoff: '2026-07-05T20:00:00Z', venue: 'Atlanta', homeCountryCode: 'FRA', awayCountryCode: 'JPN', score: null },
  { id: 'R32-7', stage: '16avos', roundIndex: 7, kickoff: '2026-07-05T23:00:00Z', venue: 'Vancouver', homeCountryCode: 'ESP', awayCountryCode: 'MAR', score: null },
  { id: 'R32-8', stage: '16avos', roundIndex: 8, kickoff: '2026-07-06T20:00:00Z', venue: 'Dallas', homeCountryCode: 'ITA', awayCountryCode: 'NED', score: null },
  { id: 'R32-9', stage: '16avos', roundIndex: 9, kickoff: '2026-07-06T23:00:00Z', venue: 'Monterrey', homeCountryCode: 'COL', awayCountryCode: 'TUR', score: null },
  { id: 'R32-10', stage: '16avos', roundIndex: 10, kickoff: '2026-07-07T20:00:00Z', venue: 'Houston', homeCountryCode: 'URU', awayCountryCode: 'ALG', score: null },
  { id: 'R32-11', stage: '16avos', roundIndex: 11, kickoff: '2026-07-07T23:00:00Z', venue: 'Philadelphia', homeCountryCode: 'POR', awayCountryCode: 'KOR', score: null },
  { id: 'R32-12', stage: '16avos', roundIndex: 12, kickoff: '2026-07-08T20:00:00Z', venue: 'San Diego', homeCountryCode: 'BEL', awayCountryCode: 'QAT', score: null },
  { id: 'R32-13', stage: '16avos', roundIndex: 13, kickoff: '2026-07-08T23:00:00Z', venue: 'Chicago', homeCountryCode: 'SUI', awayCountryCode: 'EGY', score: null },
  { id: 'R32-14', stage: '16avos', roundIndex: 14, kickoff: '2026-07-09T20:00:00Z', venue: 'Kansas City', homeCountryCode: 'DEN', awayCountryCode: 'NGA', score: null },
  { id: 'R32-15', stage: '16avos', roundIndex: 15, kickoff: '2026-07-09T23:00:00Z', venue: 'Guadalajara', homeCountryCode: 'POL', awayCountryCode: 'IRN', score: null },
  { id: 'R32-16', stage: '16avos', roundIndex: 16, kickoff: '2026-07-10T20:00:00Z', venue: 'Ciudad de México', homeCountryCode: 'CHL', awayCountryCode: 'PAR', score: null },

  // OCTAVOS
  { id: 'R16-1', stage: 'Octavos', roundIndex: 1, kickoff: '2026-07-11T20:00:00Z', venue: 'Los Angeles', homeCountryCode: 'ARG', awayCountryCode: 'BRA', score: null },
  { id: 'R16-2', stage: 'Octavos', roundIndex: 2, kickoff: '2026-07-11T23:00:00Z', venue: 'Miami', homeCountryCode: 'MEX', awayCountryCode: 'ENG', score: null },
  { id: 'R16-3', stage: 'Octavos', roundIndex: 3, kickoff: '2026-07-12T20:00:00Z', venue: 'Toronto', homeCountryCode: 'FRA', awayCountryCode: 'ESP', score: null },
  { id: 'R16-4', stage: 'Octavos', roundIndex: 4, kickoff: '2026-07-12T23:00:00Z', venue: 'Dallas', homeCountryCode: 'ITA', awayCountryCode: 'COL', score: null },
  { id: 'R16-5', stage: 'Octavos', roundIndex: 5, kickoff: '2026-07-13T20:00:00Z', venue: 'Houston', homeCountryCode: 'URU', awayCountryCode: 'POR', score: null },
  { id: 'R16-6', stage: 'Octavos', roundIndex: 6, kickoff: '2026-07-13T23:00:00Z', venue: 'Philadelphia', homeCountryCode: 'BEL', awayCountryCode: 'SUI', score: null },
  { id: 'R16-7', stage: 'Octavos', roundIndex: 7, kickoff: '2026-07-14T20:00:00Z', venue: 'Chicago', homeCountryCode: 'DEN', awayCountryCode: 'POL', score: null },
  { id: 'R16-8', stage: 'Octavos', roundIndex: 8, kickoff: '2026-07-14T23:00:00Z', venue: 'Ciudad de México', homeCountryCode: 'CHL', awayCountryCode: 'USA', score: null },

  // CUARTOS
  {
    id: 'QF-1',
    stage: 'Cuartos',
    roundIndex: 1,
    kickoff: '2026-07-07T20:00:00Z',
    venue: 'Dallas',
    homeCountryCode: 'BRA',
    awayCountryCode: 'FRA',
    score: null,
  },

  // SEMI
  {
    id: 'SF-1',
    stage: 'Semifinal',
    roundIndex: 1,
    kickoff: '2026-07-14T20:00:00Z',
    venue: 'Atlanta',
    homeCountryCode: 'ARG',
    awayCountryCode: 'BRA',
    score: null,
  },

  // FINAL
  {
    id: 'FINAL',
    stage: 'Final',
    roundIndex: 1,
    kickoff: '2026-07-19T20:00:00Z',
    venue: 'Nueva York',
    homeCountryCode: 'ARG',
    awayCountryCode: 'FRA',
    score: null,
  },
];